apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20231106083733.0.0+build.02e9424
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20231106083733.0.0+build.02e9424
  releaseNotes: |
    Release v20231106083733.0.0+build.02e9424 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-06-11-2023-08-03-35-517989259/where-for-dinner-search-my-apps-bundle@sha256:9860687958ede288a88195b140e3db8b3cbc3f2e8bf1a4db9514169c3a0e2eb6
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

