apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-ui.my-apps.tap.20231106083806.0.0+build.02e9424
spec:
  refName: where-for-dinner-ui.my-apps.tap
  version: 20231106083806.0.0+build.02e9424
  releaseNotes: |
    Release v20231106083806.0.0+build.02e9424 of package where-for-dinner-ui.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-06-11-2023-08-03-35-517989259/where-for-dinner-ui-my-apps-bundle@sha256:9925ad60e1afb4f537c117a74d85902c0400595a6434238929d5e157c3145971
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

