apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20231106083729.0.0+build.02e9424
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20231106083729.0.0+build.02e9424
  releaseNotes: |
    Release v20231106083729.0.0+build.02e9424 of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-06-11-2023-08-03-35-517989259/where-for-dinner-search-proc-my-apps-bundle@sha256:7ae60162496a13dfc8c220d67aa96daccffb357264a5247aeb87ce4ac91f02d9
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

