apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-notify.my-apps.tap.20231106083725.0.0+build.02e9424
spec:
  refName: where-for-dinner-notify.my-apps.tap
  version: 20231106083725.0.0+build.02e9424
  releaseNotes: |
    Release v20231106083725.0.0+build.02e9424 of package where-for-dinner-notify.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-06-11-2023-08-03-35-517989259/where-for-dinner-notify-my-apps-bundle@sha256:c238230518a8bcc02a28fa22c65e3a5abf7b4f05db80b2e700fc053b0e531a73
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

